krest:
  mq-server:
    conn-type: tcp
    start-port: 9003
    is-push-mode: true

  cluster:
    - localhost:9002
    - localhost:9003

      
  cache-file:
    enable-cache: true
    # 存放队列信息的文件
    queue-info:  E:\\Data\\krest-mq\\queue-info
    # 文件存放的目录
    queue-data: E:\\Data\\krest-mq\\queue-data\\
    # 单个缓存文件的大小，单位字节 4048 也就是 4 * 1024, 4 KB
    max-size: 4048
    # 单个队列缓存的文件数量
    amount: 5
