package com.krest.mq.core.entity;

public enum MsgStatus {
    SEND_TO_SERVER,
    SEND_TO_SERVER_SUCCESS,

    STAY_IN_SERVER,
    SEND_TO_CONSUMER,

    CONSUMER_CONNECT_SERVER,
    CONSUMER_CONNECT_SERVER_SUCCESS,

    PRODUCER_CONNECT_SERVER,
    PRODUCER_CONNECT_SERVER_SUCCESS;
}
