server:
  port: 8001


spring:
  application:
    name: mqServer



# krest-mq 配置
krest:
  mq-server:
    port: 9001
    is-push-mode: true
    cluster:
      - localhost:9002
      - localhost:9003
    kid: 1
    # 持久化文件存放的目录
    cacheFolder: E:\\Data\\krest-mq\\queue-data\\
    # 单个缓存文件的大小，单位字节 4048 也就是 4 * 1024, 4 KB 10 mb 10485760
    maxFileSize: 10485760
    # 单个队列缓存的文件数量
    maxFileCount: 100

