server:
  port: 8003

spring:
  application:
    name: consumer
  profiles:
    active: dev


krest:
  mq:
    workerId: 1
    datacenterId: 3
    server:
      - localhost:9001
      - localhost:9002
      - localhost:9003
    # 将要发消息的队列
    queue:
      - demo
      - demo1
      - demo2
      - demo3
