server:
  port: 8002

spring:
  application:
    name: producer
  profiles:
    active: dev

krest:
  mq:
    workerId: 1
    datacenterId: 1
    server:
      - localhost:9001
#      - localhost:9002